### ISSUE TITLE
Language Config.

### ISSUE THREAD

**Issue by detmach** [rnielikki/IRCBot#1]
UTF8 write read

**Comment by rnielikki** [comment]
Thank you for reporting! Now it works on UTF-8. (7e3c64d) If it still doesn't work, try changing your font.
User-defined encoding can be added in the future.

**Comment by detmach** [comment]
I am so sorry, I guess I couldn't explain it. There is no problem with the console screen.
IRC Chat Screen, etc. in Turkish. UTF8 does not read characters correctly. 
Image = https://i.imgyukle.com/2019/07/18/k8tMAt.png 
Sorry for bad english
Thanks
